name: Python CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Java
        run: sudo apt-get install -y openjdk-11-jdk

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyspark pytest pandas pytest-html

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run transformation script with HTML report
        run: |
          mkdir -p reports
          pytest test_cases/ --html=reports/report.html --self-contained-html
        continue-on-error: true

      - name: Set output
        if: success() || failure()
        id: results
        run: echo "artifactPath=reports/" >> $GITHUB_OUTPUT

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-report
          path: ${{ steps.results.outputs.artifactPath }}

      - name: Build project
        run: |
          mkdir -p build
          echo "This is a build output" > build/output.txt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/

  download:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download test report artifact
        uses: actions/download-artifact@v3
        with:
          name: test-report
          path: downloaded-test-report/

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: downloaded-build-artifacts/
          
