name: Run Transformation Script

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  run-transformation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Specify the Python version you need

    - name: Install Java
      run: sudo apt-get install -y openjdk-11-jdk  # Required for PySpark

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyspark pytest pandas
      

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Run transformation script
      run: python transformation/transformation_class.py
