name: Run Transformation Script

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  run-transformation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Java
      run: sudo apt-get install -y openjdk-11-jdk

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyspark pytest pandas pytest-html

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Run transformation script with HTML report
      run: pytest test_cases/ --html=report.html

    - name: Upload HTML report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: report.html
